function FCArticulationDef_ValueTests_ItemNo1(articdef)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "AboveSymbolChar", 46)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AboveUsesMain", true)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AlwaysPlaceOutsideStaff", false)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AttachToTopNote", false)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AttackIsPercent", false)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "AutoPosSide", finale.ARTPOS_AUTO_NOTESTEM)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AvoidStaffLines", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "BelowSymbolChar", 46)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "BelowUsesMain", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "BottomAttack", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "BottomDuration", 40)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "BottomVelocity", 0)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "CenterHorizontally", true)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "CopyMainSymbol", false)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "CopyMainSymbolHorizontally", false)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "DefaultVerticalPos", 16)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "DurationIsPercent", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedHandleHorizontalOffset", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedHandleVerticalOffset", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolChar", 46)
   StringValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolFont", "Maestro")
   BoolValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolIsShape", false)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolShapeID", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolSize", 24)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "InsideSlurs", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainHandleHorizontalOffset", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainHandleVerticalOffset", -4)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolChar", 46)
   StringValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolFont", "Maestro")
   BoolValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolIsShape", false)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolShapeID", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolSize", 24)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "OnScreenOnly", false)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "OnStemDistanceFromStemEnd", 0)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "Playback", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "TopAttack", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "TopDuration", 40)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "TopVelocity", 0)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "VelocityIsPercent", false)
end


-- Call:
local articdef = finale.FCArticulationDef()
AssureTrue(articdef:Load(1))
FCArticulationDef_ValueTests_ItemNo1(articdef)

function FCArticulationDef_ValueTests_ItemNo63(obj)
   NumberValuePropertyTest(obj, "FCArticulationDef", "AboveSymbolChar", 190)
   BoolValuePropertyTest(obj, "FCArticulationDef", "AboveUsesMain", true)
   BoolValuePropertyTest(obj, "FCArticulationDef", "AlwaysPlaceOutsideStaff", false)
   BoolValuePropertyTest(obj, "FCArticulationDef", "AttachToTopNote", false)
   BoolValuePropertyTest(obj, "FCArticulationDef", "AttackIsPercent", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "AutoPosSide", 6)
   BoolValuePropertyTest(obj, "FCArticulationDef", "AvoidStaffLines", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "BelowSymbolChar", 190)
   BoolValuePropertyTest(obj, "FCArticulationDef", "BelowUsesMain", true)
   NumberValuePropertyTest(obj, "FCArticulationDef", "BottomAttack", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "BottomDuration", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "BottomVelocity", 0)
   BoolValuePropertyTest(obj, "FCArticulationDef", "CenterHorizontally", false)
   BoolValuePropertyTest(obj, "FCArticulationDef", "CenterOnStemWhenStemSide", false)
   BoolValuePropertyTest(obj, "FCArticulationDef", "CopyMainSymbol", false)
   BoolValuePropertyTest(obj, "FCArticulationDef", "CopyMainSymbolHorizontally", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "DefaultVerticalPos", 24)
   BoolValuePropertyTest(obj, "FCArticulationDef", "DurationIsPercent", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "FlippedHandleHorizontalOffset", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "FlippedHandleVerticalOffset", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "FlippedSymbolChar", 190)
   StringValuePropertyTest(obj, "FCArticulationDef", "FlippedSymbolFont", "Maestro")
   BoolValuePropertyTest(obj, "FCArticulationDef", "FlippedSymbolIsShape", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "FlippedSymbolShapeID", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "FlippedSymbolSize", 24)
   BoolValuePropertyTest(obj, "FCArticulationDef", "InsideSlurs", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "MainHandleHorizontalOffset", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "MainHandleVerticalOffset", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "MainSymbolChar", 190)
   StringValuePropertyTest(obj, "FCArticulationDef", "MainSymbolFont", "Maestro")
   BoolValuePropertyTest(obj, "FCArticulationDef", "MainSymbolIsShape", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "MainSymbolShapeID", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "MainSymbolSize", 24)
   BoolValuePropertyTest(obj, "FCArticulationDef", "OnScreenOnly", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "OnStemDistanceFromStemEnd", 26)
   BoolValuePropertyTest(obj, "FCArticulationDef", "Playback", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "SlurInteraction", 0)
   BoolValuePropertyTest(obj, "FCArticulationDef", "StackAutomatically", false)
   BoolValuePropertyTest(obj, "FCArticulationDef", "StemSideWhenMultipleLayers", false)
   NumberValuePropertyTest(obj, "FCArticulationDef", "TopAttack", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "TopDuration", 0)
   NumberValuePropertyTest(obj, "FCArticulationDef", "TopVelocity", 0)
   BoolValuePropertyTest(obj, "FCArticulationDef", "VelocityIsPercent", false)
end

if not Is26OrAbove() then
    return
end

-- Call:
local obj = finale.FCArticulationDef()
AssureTrue(obj:Load(63), "FCArticulationDef:Load(63)")
FCArticulationDef_ValueTests_ItemNo63(obj)
