function FCStaff_ValueTests_ItemNo1(staff)
   NumberValuePropertyTest(staff, "FCStaff", "AutoNumberingStyle", 4)
   BoolValuePropertyTest(staff, "FCStaff", "UseAutoNumberingStyle", true)
   -- __FCStaffBase
   BoolValuePropertyTest(staff, "FCStaff", "AllowHiding", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltNotationDisplayOtherLayerNotes", true)
   NumberValuePropertyTest(staff, "FCStaff", "AltNotationLayer", 1)
   NumberValuePropertyTest(staff, "FCStaff", "AltNotationStyle", 0)
   BoolValuePropertyTest(staff, "FCStaff", "AltRhythmStemsUp", false)
   BoolValuePropertyTest(staff, "FCStaff", "AltShowArticulations", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltShowExpression", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltShowLyrics", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltShowOtherArticulations", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltShowOtherExpressions", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltShowOtherLyrics", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltShowOtherNotes", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltShowOtherSmartShapes", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltShowSmartShapes", true)
   BoolValuePropertyTest(staff, "FCStaff", "AltSlashDots", false)
   NumberValuePropertyTest(staff, "FCStaff", "BottomBarlineOffset", 0)
   NumberValuePropertyTest(staff, "FCStaff", "BottomRepeatDotPosition", -5)
   BoolValuePropertyTest(staff, "FCStaff", "BreakBarlines", false)
   BoolValuePropertyTest(staff, "FCStaff", "BreakRepeatBarlines", false)
   BoolValuePropertyTest(staff, "FCStaff", "BreakTablatureLines", false)
   NumberValuePropertyTest(staff, "FCStaff", "CapoPosition", 0)
   NumberValuePropertyTest(staff, "FCStaff", "DefaultClef", 0)
   BoolValuePropertyTest(staff, "FCStaff", "DisplayEmptyRests", true)
   NumberValuePropertyTest(staff, "FCStaff", "DoubleWholeRestPosition", -4)
   BoolValuePropertyTest(staff, "FCStaff", "FlatBeams", false)
   NumberValuePropertyTest(staff, "FCStaff", "FretInstrumentDefID", 0)
   BoolValuePropertyTest(staff, "FCStaff", "FretLetters", false)
   NumberValuePropertyTest(staff, "FCStaff", "HalfRestPosition", -4)
   NumberValuePropertyTest(staff, "FCStaff", "HideMode", 0)
   BoolValuePropertyTest(staff, "FCStaff", "IgnoreKeySig", false)
   BoolValuePropertyTest(staff, "FCStaff", "IndependentFont", false)
   BoolValuePropertyTest(staff, "FCStaff", "IndependentKeySig", false)
   BoolValuePropertyTest(staff, "FCStaff", "IndependentTimeSig", false)
   StringValuePropertyTest(staff, "FCStaff", "InstrumentUUID", "a925648a-abc9-4dc7-a619-a6ce355ad33c")
   NumberValuePropertyTest(staff, "FCStaff", "LineCount", 5)
   NumberValuePropertyTest(staff, "FCStaff", "LineSpacing", 1536)
   NumberValuePropertyTest(staff, "FCStaff", "LowestFret", 0)
   BoolValuePropertyTest(staff, "FCStaff", "NoKeySigShowAccidentals", false)
   NumberValuePropertyTest(staff, "FCStaff", "NotationStyle", 0)
   NumberValuePropertyTest(staff, "FCStaff", "OtherRestPosition", -4)
   BoolValuePropertyTest(staff, "FCStaff", "RedisplayOtherLayerAccidentals", false)
   BoolValuePropertyTest(staff, "FCStaff", "ShowAugmentationDots", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowBarlines", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowBeams", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowBottomRepeatDot", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowChords", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowClefs", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowFretboards", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowKeySignatures", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowLyrics", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowMeasureNumbers", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowNoteColors", false)
   BoolValuePropertyTest(staff, "FCStaff", "ShowNoteShapes", false)
   BoolValuePropertyTest(staff, "FCStaff", "ShowOnlyFirstMeasureClef", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowPartStaffNames", false)
   BoolValuePropertyTest(staff, "FCStaff", "ShowPartTimeSignatures", false)
   BoolValuePropertyTest(staff, "FCStaff", "ShowRepeats", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowRests", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowScoreStaffNames", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowScoreTimeSignatures", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowStaffLines", false)
   BoolValuePropertyTest(staff, "FCStaff", "ShowStems", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowTextRepeats", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowTies", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowTimeSignatures", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowTopRepeatDot", true)
   BoolValuePropertyTest(staff, "FCStaff", "ShowTuplets", true)
   NumberValuePropertyTest(staff, "FCStaff", "StemReversalPosition", -4)
   NumberValuePropertyTest(staff, "FCStaff", "StemsDirection", 1)
   NumberValuePropertyTest(staff, "FCStaff", "StemsDownHorizontalOffset", 0)
   NumberValuePropertyTest(staff, "FCStaff", "StemsDownVerticalOffsetForBeamEnd", 256)
   NumberValuePropertyTest(staff, "FCStaff", "StemsDownVerticalOffsetForNoteheadEnd", 128)
   BoolValuePropertyTest(staff, "FCStaff", "StemsNoteheadEndFixedToStaff", true)
   NumberValuePropertyTest(staff, "FCStaff", "StemsUpHorizontalOffset", 0)
   NumberValuePropertyTest(staff, "FCStaff", "StemsUpVerticalOffsetForBeamEnd", 192)
   NumberValuePropertyTest(staff, "FCStaff", "StemsUpVerticalOffsetForNoteheadEnd", 64)
   BoolValuePropertyTest(staff, "FCStaff", "StemsUseVerticalOffsetForBeamEnd", false)
   BoolValuePropertyTest(staff, "FCStaff", "StemsUseVerticalOffsetForNoteheadEnd", false)
   NumberValuePropertyTest(staff, "FCStaff", "TopBarlineOffset", 0)
   NumberValuePropertyTest(staff, "FCStaff", "TopRepeatDotPosition", -3)
   NumberValuePropertyTest(staff, "FCStaff", "TransposeAlteration", 0)
   BoolValuePropertyTest(staff, "FCStaff", "TransposeChromatic", false)
   NumberValuePropertyTest(staff, "FCStaff", "TransposeClefIndex", 0)
   NumberValuePropertyTest(staff, "FCStaff", "TransposeInterval", 0)
   BoolValuePropertyTest(staff, "FCStaff", "TransposeSimplifyKey", true)
   BoolValuePropertyTest(staff, "FCStaff", "TransposeUseClef", false)
   NumberValuePropertyTest(staff, "FCStaff", "VerticalFretOffset", -1024)
   NumberValuePropertyTest(staff, "FCStaff", "WholeRestPosition", -4)
   -- ___FCNoInciOther and up_
   NumberValuePropertyTest(staff, "FCStaff", "ItemNo", 1)
end

-- Call:
local staff = finale.FCStaff(not set_staff_show_part_time_sigs_not_writable)
AssureTrue(staff:Load(1), "FCStaff:Load(1)")
FCStaff_ValueTests_ItemNo1(staff)


function FCFontInfo_ValueTests_ItemNo18(indfont)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Absolute", false)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Bold", false)
   NumberValuePropertyTest(indfont, "FCFontInfo", "EnigmaStyles", 0)
   NumberValuePropertyTest(indfont, "FCFontInfo", "FontID", 18)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Hidden", false)
   BoolValuePropertyTest_RO(indfont, "FCFontInfo", "IsSMuFLFont", false)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Italic", false)
   StringValuePropertyTest(indfont, "FCFontInfo", "Name", "Maestro Wide")
   NumberValuePropertyTest(indfont, "FCFontInfo", "Size", 24)
   NumberValuePropertyTest(indfont, "FCFontInfo", "SizeFloat", 24.0)
   BoolValuePropertyTest(indfont, "FCFontInfo", "StrikeOut", false)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Underline", false)
end


-- Call:
local staff = finale.FCStaff()
staff:Load(3)
local indfont = staff:CreateIndependentFontInfo()
FCFontInfo_ValueTests_ItemNo18(indfont)
