function FCTupletPrefs_ValueTests_ItemNo1(prefs)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "AllowHorizontalDrag", false)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "AlwaysFlat", false)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "AvoidStaff", true)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "BracketFullDuration", false)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "BracketMode",finale.TUPLETBRACKET_NEVERBEAMEDONBEAMSIDE)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "BracketThickness", 115)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "BreakSlurBracket", true)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "CenterUsingDuration", false)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "EngraverTuplet", true)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "HorizontalOffset", 0)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "HorizontalShapeOffset", 0)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "IgnoreNumberOffset", false)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "LeftExtension", 0)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "LeftHookLength", 12)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "MatchHookLengths", true)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "MaxSlope", 100)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "NumberOffsetDownstem", -10)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "NumberOffsetUpstem", 10)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "NumberStyle", finale.TUPLETNUMBER_REGULAR)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "PlacementMode", finale.TUPLETPLACEMENT_STEMSIDE)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "RightExtension", 0)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "RightHookLength", 12)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "ShapeStyle", finale.TUPLETSHAPE_BRACKET)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "SlopeAdjust", 0)
   BoolValuePropertyTest(prefs, "FCTupletPrefs", "UseBottomNote", false)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "VerticalOffset", 24)
   NumberValuePropertyTest(prefs, "FCTupletPrefs", "VerticalShapeOffset", 0)
end


-- Call:
local prefs = finale.FCTupletPrefs()
AssureTrue(prefs:Load(1), "FCTupletPrefs:Load(1)")
FCTupletPrefs_ValueTests_ItemNo1(prefs)
