function FCStaffStyleDef_ValueTests_ItemNo1(ssd)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "AddToMenu", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "AllowHiding", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "AltNotationDisplayOtherLayerNotes", true)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "AltNotationLayer", 4)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "AltNotationStyle", finale.ALTSTAFF_BLANKNOTATION)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "BottomBarlineOffset", 0)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "BreakBarlines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "BreakRepeatBarlines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "BreakTablatureLines", false)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "CapoPosition", 0)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "Copyable", true)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "DefaultClef", 0)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "DisplayEmptyRests", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "FlatBeams", false)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "FretInstrumentDefID", 0)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "FretLetters", false)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "HideMode", finale.STAFFHIDE_NORMAL)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "IgnoreKeySig", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "IndependentFont", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "IndependentKeySig", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "IndependentTimeSig", false)
   StringValuePropertyTest(ssd, "FCStaffStyleDef", "InstrumentUUID", "00000000-4627-4100-abbf-064eedc15fe3")
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "LineCount", 5)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "LowestFret", 0)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "NoKeySigShowAccidentals", false)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "NotationStyle", finale.STAFFNOTATION_NORMAL)      
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "RedisplayOtherLayerAccidentals", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowAugmentationDots", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowBarlines", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowBeams", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowChords", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowClefs", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowFretboards", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowKeySignatures", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowLyrics", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowMeasureNumbers", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowNoteColors", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowNoteShapes", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowOnlyFirstMeasureClef", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowPartStaffNames", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowRepeats", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowRests", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowScoreStaffNames", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowStaffLines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowStems", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowTextRepeats", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowTies", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowTimeSignatures", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "ShowTuplets", true)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "TopBarlineOffset", 0)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "TransposeAlteration", 0)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "TransposeChromatic", false)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "TransposeClefIndex", 0)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "TransposeInterval", 0)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "TransposeSimplifyKey", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "TransposeUseClef", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseAbbreviatedName", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseAbbreviatedPosition", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseAllowHiding", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseAltNotationStyle", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseBreakBarlines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseBreakRepeatBarlines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseDefaultClef", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseDisplayEmptyRests", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseFlatBeams", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseFullName", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseFullNamePosition", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseHideMode", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseIgnoreKeySig", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseIndependentFont", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseIndependentKeySig", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseIndependentTimeSig", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseNoKeySigShowAccidentals", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseNotationStyle", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseRedisplayOtherLayerAccidentals", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowAugmentationDots", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowBarlines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowChords", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowClefs", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowFretboards", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowKeySignatures", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowLyrics", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowMeasureNumbers", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowNoteColors", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowNoteShapes", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowPartStaffNames", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowRepeats", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowRests", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowScoreStaffNames", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowStaffLines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowStems", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowTextRepeats", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowTies", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowTimeSignatures", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseStafflineAdjustments", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseTransposition", false)
   NumberValuePropertyTest(ssd, "FCStaffStyleDef", "VerticalFretOffset", 0)
end

-- Call:
local ssd1 = finale.FCStaffStyleDef()
AssureTrue(ssd1:Load(1), "FCStaffStyleDef:Load(1)")
FCStaffStyleDef_ValueTests_ItemNo1(ssd1)



function FCStaffStyleDef_ValueTests_ItemNo30(ssd)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "AddToMenu", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "Copyable", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseAbbreviatedName", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseAbbreviatedPosition", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseAllowHiding", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseAltNotationStyle", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseBreakBarlines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseBreakRepeatBarlines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseDefaultClef", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseDisplayEmptyRests", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseFlatBeams", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseFullName", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseFullNamePosition", true)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseHideMode", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseIgnoreKeySig", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseIndependentFont", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseIndependentKeySig", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseIndependentTimeSig", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseNoKeySigShowAccidentals", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseNotationStyle", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseRedisplayOtherLayerAccidentals", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowAugmentationDots", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowBarlines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowChords", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowClefs", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowFretboards", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowKeySignatures", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowLyrics", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowMeasureNumbers", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowNoteColors", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowNoteShapes", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowPartStaffNames", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowRepeats", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowRests", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowScoreStaffNames", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowStaffLines", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowStems", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowTextRepeats", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowTies", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseShowTimeSignatures", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseStafflineAdjustments", false)
   BoolValuePropertyTest(ssd, "FCStaffStyleDef", "UseTransposition", false)
end

function FCStaffNamePosition_ValueTests_ItemNo30_Full(ssd_full)
   NumberValuePropertyTest(ssd_full, "FCStaffNamePosition", "Alignment", 2)
   BoolValuePropertyTest(ssd_full, "FCStaffNamePosition", "ExpandSingleWord", false)
   NumberValuePropertyTest(ssd_full, "FCStaffNamePosition", "HorizontalOffset", -144)
   NumberValuePropertyTest(ssd_full, "FCStaffNamePosition", "Justification", 2)
   BoolValuePropertyTest(ssd_full, "FCStaffNamePosition", "UsePositioning", true)
   NumberValuePropertyTest(ssd_full, "FCStaffNamePosition", "VerticalOffset", -16)
end

function FCStaffNamePosition_ValueTests_ItemNo30_Abbrv(ssd_abbr)
   NumberValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "Alignment", 2)
   BoolValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "ExpandSingleWord", false)
   NumberValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "HorizontalOffset", -72)
   NumberValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "Justification", 2)
   BoolValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "UsePositioning", true)
   NumberValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "VerticalOffset", -16)
end


-- Call:
local ssd2 = finale.FCStaffStyleDef()
AssureTrue(ssd2:Load(30), "FCStaffStyleDef:Load(30)")
FCStaffStyleDef_ValueTests_ItemNo30(ssd2)
if AssureNonNil(ssd2.GetFullNamePosition, "FCStaffStyleDef.GetFullNamePosition is nil") then
    FCStaffNamePosition_ValueTests_ItemNo30_Full(ssd2:GetFullNamePosition())
end
if AssureNonNil(ssd2.GetAbbreviatedNamePosition, "FCStaffStyleDef.GetAbbreviatedNamePosition is nil") then
    FCStaffNamePosition_ValueTests_ItemNo30_Abbrv(ssd2:GetAbbreviatedNamePosition())
end


function FCStaffNamePosition_ValueTests_ItemNo31_Full(ssd_full)
   NumberValuePropertyTest(ssd_full, "FCStaffNamePosition", "Alignment", 1)
   BoolValuePropertyTest(ssd_full, "FCStaffNamePosition", "ExpandSingleWord", false)
   NumberValuePropertyTest(ssd_full, "FCStaffNamePosition", "HorizontalOffset", -73)
   NumberValuePropertyTest(ssd_full, "FCStaffNamePosition", "Justification", 1)
   BoolValuePropertyTest(ssd_full, "FCStaffNamePosition", "UsePositioning", false)
   NumberValuePropertyTest(ssd_full, "FCStaffNamePosition", "VerticalOffset", -16)
end

function FCStaffNamePosition_ValueTests_ItemNo31_Abbrv(ssd_abbr)
   NumberValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "Alignment", 1)
   BoolValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "ExpandSingleWord", false)
   NumberValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "HorizontalOffset", -72)
   NumberValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "Justification", 1)
   BoolValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "UsePositioning", false)
   NumberValuePropertyTest(ssd_abbr, "FCStaffNamePosition", "VerticalOffset", -17)
end


-- Call:
if AssureNonNil(ssd2.GetFullNamePosition, "FCStaffStyleDef.GetFullNamePosition is nil") then
    local obj = finale.FCStaffStyleDef()
    obj:SetName(finale.FCString("Position Adjust Creator"))
    AssureTrue(obj:SaveNew(), "FCStaffStyleDef.SaveNew for name position test.")
    BoolValuePropertyTest(obj, "FCStaffStyleDef", "UseAbbreviatedPosition", false)
    BoolValuePropertyTest(obj, "FCStaffStyleDef", "UseFullNamePosition", false)
    local fn = obj:GetFullNamePosition()
    fn.HorizontalOffset = -73
    local an = obj:GetAbbreviatedNamePosition()
    an.VerticalOffset = -17
    AssureTrue(obj:Save(), "FCStaffStyleDef.Save for name position test.")
    AssureTrue(obj:Reload(), "FCStaffStyleDef.Reload for name position test.")
    BoolValuePropertyTest(obj, "FCStaffStyleDef", "UseAbbreviatedPosition", true)
    BoolValuePropertyTest(obj, "FCStaffStyleDef", "UseFullNamePosition", true)
    FCStaffNamePosition_ValueTests_ItemNo31_Full(obj:GetFullNamePosition())
    FCStaffNamePosition_ValueTests_ItemNo31_Abbrv(obj:GetAbbreviatedNamePosition())
end


function FCFontInfo_ValueTests_ItemNo11(indfont)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Absolute", true)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Bold", false)
   NumberValuePropertyTest(indfont, "FCFontInfo", "EnigmaStyles", 0x44)
   NumberValuePropertyTest(indfont, "FCFontInfo", "FontID", 11)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Hidden", false)
   BoolValuePropertyTest_RO(indfont, "FCFontInfo", "IsSMuFLFont", false)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Italic", false)
   StringValuePropertyTest(indfont, "FCFontInfo", "Name", "Jazz")
   NumberValuePropertyTest(indfont, "FCFontInfo", "Size", 25)
   NumberValuePropertyTest(indfont, "FCFontInfo", "SizeFloat", 25.0)
   BoolValuePropertyTest(indfont, "FCFontInfo", "StrikeOut", false)
   BoolValuePropertyTest(indfont, "FCFontInfo", "Underline", true)
end


-- Call:
local obj = finale.FCStaffStyleDef()
obj:Load(31)
local indfont = obj:CreateIndependentFontInfo()
FCFontInfo_ValueTests_ItemNo11(indfont)

