local function TestClose(classname, success_expected, ...)
    local success, msg = pcall(function(...)
            local closable <close> = finale[classname](...)
        end, ...)
    if success_expected then
        AssureTrue(success, "TestClose "..classname.." returned: "..tostring(msg))
    else
        AssureFalse(success, "TestClose "..classname.." should have failed.")
    end
end

local entry = LoadMeasureEntry(6, 2, 125)
AssureNonNil(entry, "Entry for close tests.")

-- All classes that can do <close> (ToDo: special tests for commented out collection classes that can't be constructed in Lua)
TestClose("FCCellMetrics", true)
TestClose("FCEntryMetrics", true)
TestClose("FCNumbers", true)
TestClose("FCCells", true)
TestClose("FCSeparateMeasureNumbers", true)
TestClose("FCCellTexts", true)
TestClose("FCChords", true)
TestClose("FCCellGraphics", true)
TestClose("FCGroups", true)
TestClose("FCBaselines", true)
TestClose("FCArticulations", true, entry)
TestClose("FCPrimaryBeamMods", true, entry)
TestClose("FCSecondaryBeamMods", true, entry)
TestClose("FCTuplets", true, entry)
TestClose("FCVerseSyllables", true, entry)
TestClose("FCChorusSyllables", true, entry)
TestClose("FCSectionSyllables", true, entry)
TestClose("FCNoteheadMods", true, entry)
TestClose("FCAccidentalMods", true, entry)
TestClose("FCPercussionNoteMods", true, entry)
TestClose("FCTablatureNoteMods", true, entry)
TestClose("FCDotMods", true, entry)
TestClose("FCCrossStaffMods", true, entry)
TestClose("FCPerformanceMods", true, entry)
TestClose("FCStartTieMods", true, entry)
TestClose("FCEndTieMods", true, entry)
TestClose("FCClefDefs", true)
TestClose("FCParts", true)
TestClose("FCNoteEntryCell", true, 1, 1)
TestClose("FCNoteEntryLayer", true, 0, 1, 1, 1)
--TestClose("FCShapeDefInstructions", true)
--TestClose("FCPercussionMapNotes", true)
TestClose("FCPages", true)
TestClose("FCStaffSystems", true)
TestClose("FCMeasures", true)
TestClose("FCStaves", true)
TestClose("FCMeasureNumberRegions", true)
TestClose("FCArticulationDefs", true)
TestClose("FCSystemStaves", true)
TestClose("FCCategoryDefs", true)
TestClose("FCTextExpressionDefs", true)
TestClose("FCShapeExpressionDefs", true)
TestClose("FCExpressions", true)
TestClose("FCPageTexts", true)
TestClose("FCTextBlocks", true)
TestClose("FCSeparatePlacements", true)
TestClose("FCStaffStyleDefs", true)
TestClose("FCStaffStyleAssigns", true)
TestClose("FCMultiMeasureRests", true)
TestClose("FCMultiStaffInstruments", true)
TestClose("FCAllotments", true)
TestClose("FCPageGraphics", true)
TestClose("FCTextRepeatDefs", true)
TestClose("FCFretInstrumentDefs", true)
TestClose("FCTextRepeats", true)
TestClose("FCShapeDefs", true)
TestClose("FCChordSuffixElements", true)
TestClose("FCFretboardStyleDefs", true)
TestClose("FCBeatChartElements", true)
TestClose("FCTempoElements", true)
TestClose("FCPercussionLayoutNotes", true)
TestClose("FCInstrumentDefs", true)
TestClose("FCStaffLists", true)
TestClose("FCCellClefChanges", true)
--TestClose("FCGuides", true)
TestClose("FCMetatoolAssignments", true)
TestClose("FCSmartShapeMeasureMarks", true)
TestClose("FCSmartShapeEntryMarks", true, entry)
TestClose("FCCustomSmartLineDefs", true)

-- A sampling of classes that can't do close
TestClose("FCMeasure", false)
TestClose("FCCompositeTimeSigTop", false)
TestClose("FCCompositeTimeSigBottom", false)
TestClose("FCCell", false)
TestClose("FCDotMod", false)
TestClose("FCTextExpressionDef", false)
