function FCChord_PropertyTests(obj)
   NumberPropertyTest(obj, "FCChord", "Alteration", {-7, -1, 0, 1, 7})
   NumberPropertyTest(obj, "FCChord", "AlternateBassAlteration", {-7, -1, 0, 1, 7})
   NumberPropertyTest(obj, "FCChord", "AlternateBassScaleNumber", {0, 12, 31})
   NumberPropertyTest(obj, "FCChord", "Capo", {0, 4, 17, 63})
   BoolPropertyTest(obj, "FCChord", "ChordAlternateBassLowercase")
   NumberPropertyTest(obj, "FCChord", "ChordAlternateBassPlacement", {finale.ALTBASSPLACE_AFTERROOT, finale.ALTBASSPLACE_SUBTEXT, finale.ALTBASSPLACE_UNDERROOT})
   BoolPropertyTest(obj, "FCChord", "ChordAlternateBassPlayback")
   BoolPropertyTest(obj, "FCChord", "ChordAlternateBassVisible")
   NumberPropertyTest(obj, "FCChord", "ChordHorizontalPos", {-144, 0, 144})
   NumberPropertyTest(obj, "FCChord", "ChordResize", {-144, 0, 144})
   BoolPropertyTest(obj, "FCChord", "ChordRootLowercase")
   BoolPropertyTest(obj, "FCChord", "ChordRootPlayback")
   BoolPropertyTest(obj, "FCChord", "ChordRootVisible")
   NumberPropertyTest(obj, "FCChord", "ChordSuffixID", {-144, 0, 144})
   BoolPropertyTest(obj, "FCChord", "ChordSuffixPlayback")
   BoolPropertyTest(obj, "FCChord", "ChordSuffixVisible")
   NumberPropertyTest(obj, "FCChord", "ChordVerticalPos", {-144, 0, 144})
   BoolPropertyTest(obj, "FCChord", "ChordVisible")
   NumberPropertyTest(obj, "FCChord", "FretboardHorizontalPos", {-144, 0, 144})
   BoolPropertyTest(obj, "FCChord", "FretboardPlayback")
   NumberPropertyTest(obj, "FCChord", "FretboardResize", {-144, 0, 144})
   NumberPropertyTest(obj, "FCChord", "FretboardStyleID", {0, 1, 12})
   BoolPropertyTest(obj, "FCChord", "FretboardUseFont")
   NumberPropertyTest(obj, "FCChord", "FretboardVerticalPos", {-144, 0, 144})
   BoolPropertyTest(obj, "FCChord", "FretboardVisible")
   NumberPropertyTest(obj, "FCChord", "MeasurePos", {-144, 0, 144})
   NumberPropertyTest(obj, "FCChord", "ScaleNumber", {0, 12, 31})
   BoolPropertyTest(obj, "FCChord", "UseCapo")
end


-- Call:
local obj = finale.FCChord()
obj:ConnectCell(finale.FCCell(46, 1))
AssureTrue(obj:LoadFirst(), "FCChord:LoadFirst()")
FCChord_PropertyTests(obj)
