function FCStaffStyleDef_PropertyTests(ssd)
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AddToMenu")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AllowHiding")
   PropertyTest(ssd, "FCStaffStyleDef", "AltNotationDisplayOtherLayerNotes")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "AltNotationLayer", {1, 2, 3})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "AltNotationStyle", {finale.ALTSTAFF_NORMAL,
        finale.ALTSTAFF_SLASHBEATS, finale.ALTSTAFF_RHYTHMIC, finale.ALTSTAFF_ONEBARREPEAT,
        finale.ALTSTAFF_TWOBARREPEAT, finale.ALTSTAFF_BLANKNOTATION })
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltRhythmStemsUp")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltShowArticulations")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltShowExpression")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltShowLyrics")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltShowOtherArticulations")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltShowOtherExpressions")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltShowOtherLyrics")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltShowOtherNotes")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltShowOtherSmartShapes")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltShowSmartShapes")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "AltSlashDots")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "BottomBarlineOffset", {-304, 0, 304})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "BottomRepeatDotPosition", {-12, 0, 12})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "BreakBarlines")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "BreakRepeatBarlines")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "BreakTablatureLines")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "CapoPosition", {0, 3, 13})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "Copyable")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "DefaultClef", {1, 4, 9})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "DisplayEmptyRests")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "DoubleWholeRestPosition", {-12, 0, 12})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "FlatBeams")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "FretInstrumentDefID", {0, 99, 278})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "FretLetters")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "HalfRestPosition", {-12, 0, 12})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "HideMode", { finale.STAFFHIDE_NORMAL, finale.STAFFHIDE_SCORE, finale.STAFFHIDE_SCORE_AND_PARTS, finale.STAFFHIDE_CUTAWAY} )
   BoolPropertyTest(ssd, "FCStaffStyleDef", "IgnoreKeySig")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "IndependentFont")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "IndependentKeySig")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "IndependentTimeSig")
   StringPropertyTest(ssd, "FCStaffStyleDef", "InstrumentUUID", {finale.FFUUID_VIOLIN, finale.FFUUID_UNKNOWN, finale.FFUUID_PIANO})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "LineCount", {0, 1, 5})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "LowestFret", {0, 2, 9})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "NoKeySigShowAccidentals")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "NotationStyle", {finale.STAFFNOTATION_NORMAL, finale.STAFFNOTATION_PERCUSSION, finale.STAFFNOTATION_TABLATURE})   
   NumberPropertyTest(ssd, "FCStaffStyleDef", "OtherRestPosition", {-12, 0, 12})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "RedisplayOtherLayerAccidentals")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowAugmentationDots")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowBarlines")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowBeams")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowChords")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowClefs")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowFretboards")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowKeySignatures")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowLyrics")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowMeasureNumbers")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowNoteColors")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowNoteShapes")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowOnlyFirstMeasureClef")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowPartStaffNames")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowPartTimeSignatures")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowRepeats")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowRests")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowScoreStaffNames")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowScoreTimeSignatures")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowStaffLines")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowStems")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowTextRepeats")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowTies")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowTimeSignatures")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowTopRepeatDot")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "ShowTuplets")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "StemReversalPosition", {-7, 0, 11})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "StemsDirection", {finale.STAFFSTEMDIR_ALWAYS_UP, finale.STAFFSTEMDIR_ALWAYS_DOWN, finale.STAFFSTEMDIR_DEFAULT})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "StemsDownHorizontalOffset", {-11, 0, 132})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "StemsDownVerticalOffsetForBeamEnd", {-11, 0, 132})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "StemsDownVerticalOffsetForNoteheadEnd", {-11, 0, 132})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "StemsNoteheadEndFixedToStaff")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "StemsUpHorizontalOffset", {-11, 0, 132})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "StemsUpVerticalOffsetForBeamEnd", {-11, 0, 132})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "StemsUpVerticalOffsetForNoteheadEnd", {-11, 0, 132})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "StemsUseVerticalOffsetForBeamEnd")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "StemsUseVerticalOffsetForNoteheadEnd")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "TopBarlineOffset", {-267, 0, 267})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "TransposeAlteration", {-4, 0, 4})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "TransposeChromatic")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "TransposeClefIndex", {1, 4, 8})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "TransposeInterval", {-3, 0, 5} )
   BoolPropertyTest(ssd, "FCStaffStyleDef", "TransposeSimplifyKey")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "TransposeUseClef")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "TopRepeatDotPosition", {-12, 0, 12})
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseAbbreviatedName")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseAbbreviatedPosition")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseAllowHiding")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseAltNotationStyle")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseBreakBarlines")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseBreakRepeatBarlines")
   PropertyTest(ssd, "FCStaffStyleDef", "UseDefaultClef")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseDisplayEmptyRests")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseFlatBeams")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseFullName")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseFullNamePosition")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseHideMode")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseIgnoreKeySig")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseIndependentFont")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseIndependentKeySig")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseIndependentTimeSig")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseNoKeySigShowAccidentals")
   PropertyTest(ssd, "FCStaffStyleDef", "UseNotationStyle")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseRedisplayOtherLayerAccidentals")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowAugmentationDots")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowBarlines")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowChords")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowClefs")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowFretboards")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowKeySignatures")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowLyrics")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowMeasureNumbers")
   PropertyTest(ssd, "FCStaffStyleDef", "UseShowNoteColors")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowNoteShapes")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowPartStaffNames")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowPartTimeSignatures")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowRepeats")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowRests")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowScoreStaffNames")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowStaffLines")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowStems")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowTextRepeats")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowTies")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseShowTimeSignatures")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseStafflineAdjustments")
   BoolPropertyTest(ssd, "FCStaffStyleDef", "UseTransposition")
   NumberPropertyTest(ssd, "FCStaffStyleDef", "VerticalFretOffset", {-300, 0, 300})
   NumberPropertyTest(ssd, "FCStaffStyleDef", "WholeRestPosition", {-12, 0, 12})
   --
   CreatorSetterTest(ssd, "FCStaffStyleDef", "CreateIndependentFontInfo", "SetIndependentFontInfo", FCFontInfoCompare,
        {finale.FCFontInfo("Maestro Wide", 17, 0x24), finale.FCFontInfo("Courier", 23, 0x83)})
end


-- Call:
local ssd = finale.FCStaffStyleDef()
AssureTrue(ssd:Load(1), "FCStaffStyleDef:Load()")
FCStaffStyleDef_PropertyTests(ssd)
