function TestConstants_REQVERSIONTYPE_()
   NumberConstantTest(finale.REQVERSIONTYPE_MINIMUM_FINALE, "REQVERSIONTYPE_MINIMUM_FINALE", 0)
   NumberConstantTest(finale.REQVERSIONTYPE_MAXIMUM_FINALE, "REQVERSIONTYPE_MAXIMUM_FINALE", 1)
   NumberConstantTest(finale.REQVERSIONTYPE_MINIMUM_FINALE_MAJOR, "REQVERSIONTYPE_MINIMUM_FINALE_MAJOR", 2)
   NumberConstantTest(finale.REQVERSIONTYPE_MAXIMUM_FINALE_MAJOR, "REQVERSIONTYPE_MAXIMUM_FINALE_MAJOR", 3)
   NumberConstantTest(finale.REQVERSIONTYPE_MINIMUM_LUAX1000, "REQVERSIONTYPE_MINIMUM_LUAX1000", 4)
   NumberConstantTest(finale.REQVERSIONTYPE_MAXIMUM_LUAX1000, "REQVERSIONTYPE_MAXIMUM_LUAX1000", 5)
end

-- Test the constants:
TestConstants_REQVERSIONTYPE_()
